Makefile/check-local: Ensure design document exists
This way a missing design document is detected.

Signed-off-by: Michael Hanselmann <hansmi@google.com>
Reviewed-by: Iustin Pop <iustin@google.com>

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -1417,7 +1417,11 @@ check-local: check-dirs $(GENERATED_FILES)
 			echo "Incorrect version in $$file, expected $$expver"; \
 			exit 1; \
 		fi; \
-	done
+	done; \
+	if ! test -f doc/design-$$expver.rst; then \
+		echo "File doc/design-$$expver.rst not found"; \
+		exit 1; \
+	fi
 
 .PHONY: hs-check
 hs-check: htest/test htest/hpc-htools $(HS_BUILT_TEST_HELPERS)
